### PR TITLE
Use class to support to support Node.js v8.0.0

### PR DESCRIPTION
**Pull request by watilde**
Refs: https://github.com/archiverjs/node-archiver/issues/236#issuecomment-305451553

### CODE REVIEW

**Comment by watilde** [comment]
Wow  @iarna 's patch would be better than mine to support old nodejs ;)
+ https://github.com/iarna/node-crc32-stream/commit/88d4a88629b09ca59e90ec8e12a8119d5af3012e

Will close this when she makes PR. Thanks.

**Comment by watilde** [comment]
Hmm... TBH, I don't want to drop supporting v6 since it's still active as LTS: https://github.com/nodejs/LTS#lts-schedule1. I will think about the other solution.

**Comment by biofractal** [comment]
Would it be possible for you to publish this change to your npm package please?

**Comment by watilde** [comment]
@biofractal To fix the issue and keep the backwards compatibility, we need to wait for a patch in the upstream. Once [nodejs/node#13370](https://github.com/nodejs/node/pull/13370) gets merge, let's try to update again.

**Pull request closed without merging**
